paths-ignore:
  - 'system/configuration/certificates/*.key.pem'
  - 'vm/.vagrant/machines/default/virtualbox/private_key'
  - 'demos/ldap-integration/certs/ldap.key'
  - 'demos/simple-cluster/files/certs/*.key.pem'
  - 'demos/cluster/files/certs/*.key.pem'
  - 'demos/aws-authentication/*.pem'
  - 'demos/certificate-authority/mutual-tls/README.md'
  - 'curl_examples/check'
