# For setting up a decomposed Follower
version: "3"
services:
  # Seedfetcher Init Container
  seedfetcher:
    image: registry2.itci.conjur.net/cyberark/container-dap-seedfetcher:${DF_VERSION}
    networks:
      dap_net:
        ipv4_address: 12.16.23.20
    environment:
      CONJUR_ACCOUNT: demo
      CONJUR_APPLIANCE_URL: https://conjur-master.mycompany.local
      CONJUR_AUTHN_URL: https://conjur-master.mycompany.local/authn
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY: ${CONJUR_AUTHN_API_KEY}
      CONJUR_SSL_CERTIFICATE: ${CONJUR_SSL_CERTIFICATE}
      FOLLOWER_HOSTNAME: conjur-follower.mycompany.local
      MY_POD_NAMESPACE: nope
    volumes:
      - dap_config:/opt/conjur/etc/config
      - dap_datakey:/opt/conjur/etc/data_key
      - dap_certs:/opt/conjur/etc/ssl

  nginx:
    image: registry2.itci.conjur.net/cyberark/dap-nginx:${DF_VERSION}
    user: www-data:0
    networks:
      dap_net:
        ipv4_address: 12.16.23.21
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - dap_certs:/opt/conjur/etc/ssl

  pg:
    image: registry2.itci.conjur.net/cyberark/dap-postgres:${DF_VERSION}
    user: "999:0" # non-root UID specified in Dockerfile
    networks:
      dap_net:
        ipv4_address: 12.16.23.23
    volumes:
      - dap_certs:/opt/conjur/etc/ssl
      - dap_config:/opt/conjur/etc/config

  syslog-ng:
    image: registry2.itci.conjur.net/cyberark/dap-syslog-ng:${DF_VERSION}
    user: "555:0" # non-root UID specified in Dockerfile
    networks:
      dap_net:
        ipv4_address: 12.16.23.24
    volumes:
      - dap_run:/run/conjur
      - dap_certs:/opt/conjur/etc/ssl
      - dap_config:/opt/conjur/etc/config

  conjur:
    image: registry2.itci.conjur.net/cyberark/dap-conjur:${DF_VERSION}
    environment:
      CONJUR_DATABASE_HOSTNAME: pg
      DATABASE_URL: postgres://conjur@pg/conjur
    depends_on:
      - nginx
      - pg
      - syslog-ng
    volumes:
      - dap_config:/opt/conjur/etc/config
      - dap_datakey:/opt/conjur/etc/data_key
      - dap_certs:/opt/conjur/etc/ssl
      - dap_run:/run/conjur
    network_mode: service:nginx

  info:
    image: registry2.itci.conjur.net/cyberark/dap-info:${DF_VERSION}
    user: ${INFO_USERID}:0
    environment:
      CONJUR_DATABASE_HOSTNAME: pg
    volumes:
      - dap_certs:/opt/conjur/etc/ssl
      - dap_config:/opt/conjur/etc/config
    network_mode: service:nginx

volumes:
  dap_run:
  dap_config:
  dap_certs:
  dap_datakey:

networks:
  dap_net:
    external: true
