#!/bin/bash -eu

CONJUR_VERSION="0.0.dev-20250305125316-1b417d93"

main() {
  clear

  # Stand up the nodes
  echo "Setting up Conjur deployment with Leader, Standbys, and Followers..."
  echo
  bin/dap --provision-master --version "${CONJUR_VERSION}"
  bin/dap --provision-standbys --version "${CONJUR_VERSION}"
  bin/dap --provision-follower --version "${CONJUR_VERSION}"
  echo

  press_to_continue
  clear

  echo "Creating AWS dynamic secret issuers..."
  echo
  echo -e 'curl \\
    --header "Authorization: Token token="$token"" \\
    --header "Content-Type: application/json" \\
    --request POST \\
    --data '\''{
      "id": "issuer_name",
      "max_ttl": 3600,
      "type": "aws",
      "data": {
        "access_key_id": "...",
        "secret_access_key": "..."
      }
    }'\'' \\
    "$leader_url/api/issuers/$account"' | pygmentize -l bash -O style=github-dark
  echo
  bin/api --create-aws-issuer "my-aws" "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}"
  bin/api --create-aws-issuer "not-replicated" "${AWS_ACCESS_KEY_ID}" "${AWS_SECRET_ACCESS_KEY}"
  echo

  press_to_continue
  clear

  # Load the policy structure
  echo "Loading dynamic secret and replication policy..."
  echo
  echo -e '# dynamic-secret.yml
...
- !policy
  id: data/dynamic
  body:
  - !variable
    id: ds-assume-role
    annotations:
      dynamic/issuer: my-aws
      dynamic/method: assume-role
      dynamic/role_arn: "..."
      dynamic/region: us-east-1
      dynamic/inline_policy: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Action": [
                "ec2:DescribeInstances"
              ],
              "Resource": "*"
            }
          ]
        }

  - !variable
    id: ds-federation-token
    annotations:
      dynamic/issuer: my-aws
      dynamic/method: federation-token
  ...' | pygmentize -l yaml -O style=github-dark
  echo
  echo
  echo -e '# dynamic-secret-replication.yml
...
- !permit
  resource: !variable data/dynamic/ds-federation-token
  privileges: [ 'read', 'execute' ]
  role: !group
    account: system
    id: conjur/replication-sets/test/replicated-data
...' | pygmentize -l yaml -O style=github-dark
  echo
  bin/cli conjur policy load -b root -f policy/dynamic-secret.yml
  bin/cli conjur policy load -b root -f policy/dynamic-secret-replication.yml
  echo

  press_to_continue
  clear

  echo "Listing issuers on Leader..."
  echo
  echo -e 'curl \\
  --header "Authorization: Token token="$token"" \\
  "$leader_url/api/issuers/$account"' | pygmentize -l bash -O style=github-dark
  echo
  bin/api --against-master --list-issuers
  echo

  press_to_continue
  clear

  echo "Retrieving assume-role dynamic secret..."
  echo

  echo -e 'curl \\
    --header "Authorization: Token token="$token"" \\
    "$leader_url/api/secrets/$account/variable/data/dynamic/$secret_id}"' | pygmentize -l bash -O style=github-dark
  echo

  bin/api --against-master --get-dynamic-secret ds-assume-role
  echo

  press_to_continue
  clear

  echo "Retrieving federation-token dynamic secret..."
  echo
  bin/api --against-master --get-dynamic-secret ds-federation-token
  echo

  press_to_continue
  clear

  echo "Retrieving non-replicated federation token dynamic secret..."
  echo
  bin/api --against-master --get-dynamic-secret ds-not-replicated
  echo

  press_to_continue
  clear

  echo "Listing issuers on Follower..."
  echo
  bin/api --list-issuers
  echo

  press_to_continue
  clear

  echo "Retrieving assume role dynamic secret from Follower..."
  echo
  bin/api --get-dynamic-secret ds-assume-role
  echo

  press_to_continue
  clear

  echo "Retrieving federation token dynamic secret from Follower..."
  echo
  bin/api --get-dynamic-secret ds-federation-token
  echo

  press_to_continue
  clear

  # This is expected to fail, because the federated token wasn't replicated
  echo "Attempting to retrieve non-replicated federation token dynamic secret from follower..."
  echo
  bin/api --get-dynamic-secret ds-not-replicated || true
  echo

  press_to_continue
  clear

  echo "Promoting Standby..."
  echo
  bin/dap --promote-standby
  echo

  press_to_continue
  clear

  echo "Listing issuers on new Leader..."
  echo
  bin/api --against-master --list-issuers
  echo

  press_to_continue
  clear

  echo "Retrieving assume role dynamic secret from the new Leader..."
  echo
  bin/api --against-master --get-dynamic-secret ds-assume-role
  echo

  press_to_continue
  clear

  echo "Retrieving federation token dynamic secret from the new Leader..."
  echo
  bin/api --against-master --get-dynamic-secret ds-federation-token
  echo

  press_to_continue
  clear

  echo "Done!"
}

press_to_continue() {
  echo "Press any key to continue..."
  read -n 1 -s
}

main "$@"
