{
 "title": "K6 Summary",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Data Transmission", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_sent\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> sum()\n  |> yield()"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"data_received\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> sum()\n  |> yield()"
    }
   ]
  },
  {
   "title": "HTTP Requests Blocked",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_blocked\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> mean(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_blocked\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> min(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Median",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_blocked\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> median(column: \"_value\")"
      }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_blocked\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> max(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "P90",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_blocked\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.90)\n"
      }
     ]
    },
    {
     "title": "P95",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_blocked\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.95)\n"
      }
     ]
    },
    {
     "title": "Histogram",
     "type": "histogram",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 10 },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_blocked\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  \n"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Requests Connecting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_connecting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> mean(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_connecting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> min(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Median",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_connecting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> median(column: \"_value\")"
      }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_connecting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> max(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "P90",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_connecting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.90)\n"
      }
     ]
    },
    {
     "title": "P95",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_connecting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.95)\n"
      }
     ]
    },
    {
     "title": "Histogram",
     "type": "histogram",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_connecting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  \n"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Request Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Mean",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> mean(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> min(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Median",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> median(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> max(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "P90",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.90)\n"
    }
   ]
  },
  {
   "title": "P95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.95)\n"
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  \n"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (Expected Response: True)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"expected_response\"] == \"true\")\n  |> group()\n  |> mean(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"expected_response\"] == \"true\")\n  |> group()\n  |> min(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Median",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"expected_response\"] == \"true\")\n  |> group()\n  |> median(column: \"_value\")"
      }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"expected_response\"] == \"true\")\n  |> group()\n  |> max(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "P90",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"expected_response\"] == \"true\")\n  |> group()\n  |> quantile(q: 0.90)\n"
      }
     ]
    },
    {
     "title": "P95",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"expected_response\"] == \"true\")\n  |> group()\n  |> quantile(q: 0.95)\n"
      }
     ]
    },
    {
     "title": "Histogram",
     "type": "histogram",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"expected_response\"] == \"true\")  \n"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Request Receiving",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_receiving\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> mean(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_receiving\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> min(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Median",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_receiving\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> median(column: \"_value\")"
      }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_receiving\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> max(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "P90",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_receiving\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.90)\n"
      }
     ]
    },
    {
     "title": "P95",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_receiving\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.95)\n"
      }
     ]
    },
    {
     "title": "Histogram",
     "type": "histogram",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_sending\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  \n"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Request Sending",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_sending\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> mean(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_sending\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> min(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Median",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_sending\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> median(column: \"_value\")"
      }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_sending\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> max(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "P90",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_sending\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.90)\n"
      }
     ]
    },
    {
     "title": "P95",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_sending\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.95)\n"
      }
     ]
    },
    {
     "title": "Histogram",
     "type": "histogram",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_receiving\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  \n"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Request TLS Handshaking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_tls_handshaking\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> mean(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_tls_handshaking\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> min(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Median",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_tls_handshaking\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> median(column: \"_value\")"
      }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_tls_handshaking\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> max(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "P90",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_tls_handshaking\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.90)\n"
      }
     ]
    },
    {
     "title": "P95",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_tls_handshaking\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.95)\n"
      }
     ]
    },
    {
     "title": "Histogram",
     "type": "histogram",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_tls_handshaking\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  \n"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Request Waiting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Mean",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_waiting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> mean(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_waiting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> min(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Median",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_waiting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> median(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_waiting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> max(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "P90",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_waiting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.90)\n"
    }
   ]
  },
  {
   "title": "P95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_waiting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.95)\n"
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_waiting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  \n"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Est. Peak Requests per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> aggregateWindow(every: 1s, fn: count)\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> max()\n"
    }
   ]
  },
  {
   "title": "Est. Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> aggregateWindow(every: 1s, fn: count)\n"
    }
   ]
  },
  {
   "title": "Total Requests Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> count()"
    }
   ]
  },
  {
   "title": "Total Passed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_value\"] == 0)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Total Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_value\"] == 1)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Total Percent Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "failed = from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_value\"] == 1)\n  |> group()\n  |> count()\n  |> toFloat()\n  |> set(key: \"row_key\", value: \"row_key\")\n  |> set(key: \"type\", value: \"failed\")\n\ntotal = from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> count()\n  |> toFloat()\n  |> set(key: \"row_key\", value: \"row_key\")\n  |> set(key: \"type\", value: \"total\")\n\nunion(tables: [failed, total])\n  |> pivot(rowKey: [\"row_key\"], columnKey: [\"type\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with\n        _value: r.failed / r.total * 100.0\n    }))\n  |> drop(columns: [\"_start\", \"_stop\", \"row_key\", \"failed\", \"total\"])\n  |> yield()\n\n"
    }
   ]
  },
  {
   "title": "Est. Requests per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> aggregateWindow(every: 1s, fn: count)\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Est. Successful Requests per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\t|> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n\t|> filter(fn: (r) => r[\"_field\"] == \"value\")\n\t|> filter(fn: (r) => r[\"expected_response\"] == \"true\")\n\t|> group()\n\t|> drop(columns: [\"_field\", \"scenario\"])\n\t|> aggregateWindow(every: 1s, fn: count)\n\t|> filter(fn: (r) => r[\"_value\"] > 0)\n\t|> mean()"
    }
   ]
  },
  { "title": "HTTP Requests (Authn)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Authn Requests per Second (Detailed)",
   "type": "timeseries",
   "description": "Shows rps for all requests that have been grouped in code via the k6 group(\"authn\")  function",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"group\"] == \"::authn\")\n  |> drop(columns: [\"_field\", \"scenario\"])\n  |> aggregateWindow(every: 1s, fn: count)\n  |> sort(columns: [\"status\", \"error_code\"])"
    }
   ]
  },
  {
   "title": "Authn Requests Waiting (TTFB)",
   "type": "timeseries",
   "description": "Shows the waiting time (Time To First Byte) for all requests that have been grouped in code via the k6 group(\"authn\")  function",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_waiting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"group\"] == \"::authn\")\n  |> sort(columns: [\"status\", \"error_code\"])\n  \n"
    }
   ]
  },
  {
   "title": "Total AuthN Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"group\"] == \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> count()"
    }
   ]
  },
  {
   "title": "AuthN Passed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"group\"] == \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_value\"] == 0)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "AuthN Failed",
   "type": "stat",
   "description": "The number of Authn POST requests that failed. K6 HTTP requests wrapped in a group() named \"authn\" are included in this query.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"group\"] == \"::authn\")\n  |> filter(fn: (r) => r[\"_value\"] == 1)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "AuthN Percent Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "failed = from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"group\"] == \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_value\"] == 1)\n  |> group()\n  |> count()\n  |> toFloat()\n  |> set(key: \"row_key\", value: \"row_key\")\n  |> set(key: \"type\", value: \"failed\")\n\ntotal = from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"group\"] == \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> count()\n  |> toFloat()\n  |> set(key: \"row_key\", value: \"row_key\")\n  |> set(key: \"type\", value: \"total\")\n\nunion(tables: [failed, total])\n  |> pivot(rowKey: [\"row_key\"], columnKey: [\"type\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with\n        _value: r.failed / r.total * 100.0\n    }))\n  |> drop(columns: [\"_start\", \"_stop\", \"row_key\", \"failed\", \"total\"])\n  |> yield()\n\n"
    }
   ]
  },
  {
   "title": "Est. AuthN Requests per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"group\"] == \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> aggregateWindow(every: 1s, fn: count)\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Est. Successful AuthN Requests per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"group\"] == \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"expected_response\"] == \"true\")\n  |> group()\n  |> drop(columns: [\"_field\", \"scenario\"])\n  |> aggregateWindow(every: 1s, fn: count)\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> mean()"
    }
   ]
  },
  { "title": "HTTP Requests (Non-Authn)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Non-Authn Requests per Second (Detailed)",
   "type": "timeseries",
   "description": "Shows all requests per second that are not a part of the authn k6 group in code",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"group\"] != \"::authn\")\n  |> drop(columns: [\"_field\", \"scenario\"])\n  |> aggregateWindow(every: 1s, fn: count)\n  |> sort(columns: [\"status\", \"error_code\"])"
    }
   ]
  },
  {
   "title": "Non-Authn Requests Waiting (TTFB)",
   "type": "timeseries",
   "description": "Shows the waiting time (Time To First Byte) for all requests that have been grouped in code via the k6 group()  function that is not the \"authn\" group",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_waiting\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"group\"] != \"::authn\")\n  |> sort(columns: [\"status\", \"error_code\"])\n  \n"
    }
   ]
  },
  {
   "title": "Total Non-AuthN Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"group\"] != \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> count()"
    }
   ]
  },
  {
   "title": "Non-AuthN Passed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"group\"] != \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_value\"] == 0)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Non-AuthN Failed",
   "type": "stat",
   "description": "The number of non-authentication related requests that failed.  K6 HTTP requests wrapped in a group() named \"authn\" are NOT included in this query.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"group\"] != \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_value\"] == 1)\n  |> group()\n  |> count()\n"
    }
   ]
  },
  {
   "title": "Non-AuthN Percent Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "failed = from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"group\"] != \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_value\"] == 1)\n  |> group()\n  |> count()\n  |> toFloat()\n  |> set(key: \"row_key\", value: \"row_key\")\n  |> set(key: \"type\", value: \"failed\")\n\ntotal = from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\n  |> filter(fn: (r) => r[\"group\"] != \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> count()\n  |> toFloat()\n  |> set(key: \"row_key\", value: \"row_key\")\n  |> set(key: \"type\", value: \"total\")\n\nunion(tables: [failed, total])\n  |> pivot(rowKey: [\"row_key\"], columnKey: [\"type\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ r with\n        _value: r.failed / r.total * 100.0\n    }))\n  |> drop(columns: [\"_start\", \"_stop\", \"row_key\", \"failed\", \"total\"])\n  |> yield()\n\n"
    }
   ]
  },
  {
   "title": "Est. Non-AuthN Requests per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"group\"] != \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> aggregateWindow(every: 1s, fn: count)\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Est. Successful Non-AuthN Requests per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"group\"] != \"::authn\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"expected_response\"] == \"true\")\n  |> group()\n  |> drop(columns: [\"_field\", \"scenario\"])\n  |> aggregateWindow(every: 1s, fn: count)\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> mean()\n"
    }
   ]
  },
  {
   "title": "Iteration Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iteration_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> mean(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iteration_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> min(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "Median",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iteration_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> median(column: \"_value\")"
      }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iteration_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> max(column: \"_value\")\n"
      }
     ]
    },
    {
     "title": "P90",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iteration_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.90)\n"
      }
     ]
    },
    {
     "title": "P95",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iteration_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> quantile(q: 0.95)\n"
      }
     ]
    },
    {
     "title": "Histogram",
     "type": "histogram",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iteration_duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  \n"
      }
     ]
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"iterations\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> count()\n"
      }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> min()\n"
      }
     ]
    }
   ]
  },
  {
   "title": "VUs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> mean()\n"
      }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group()\n  |> max()\n"
      }
     ]
    }
   ]
  },
  { "title": "Custom", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "HTTP Error Code Groups",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "query": "\t\t\tfrom(bucket: \"k6\")\n\t\t\t  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n\t\t\t  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_duration\")\n\t\t\t  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n\t\t\t  |> group(columns: [\"status\"])\n\t\t\t  |> count()\n\t\t\t  |> group()\n"
    }
   ]
  },
  {
   "title": "K6 Errors Code Groups",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"status\"] == \"0\")\n  |> group(columns: [\"error\", \"error_code\"])\n  |> count()\n  |> group()\n  |> drop(columns: [\"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Error Code Groups (Incl. k6)",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"status\", \"error_code\"])\n  |> count()\n  |> group()\n  |> drop(columns: [\"_start\", \"_stop\"])"
    }
   ]
  },
  {
   "title": "Count of HTTP Request URLs",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")  \n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"name\"])\n  |> count()\n  |> group()\n  |> drop(columns: [\"_start\", \"_stop\"])\n  |> sort(columns: [\"name\"])\n  |> yield(name: \"output\")\n"
    }
   ]
  }
 ]
}