- !policy
  id: vault-synchronizer-hosts
  body:
    - !host safe-1
    - !host safe-2
    - !host safe-3
    - !host safe-4
    - !host safe-5

- !grant
  role: !group vault-synchronizer/lob-1/safe-1/consumers
  member: !host vault-synchronizer-hosts/safe-1

- !grant
  role: !host vault-synchronizer-hosts/safe-1
  member: !group
    account: system
    id: /conjur/replication-sets/replication-set-1/replicated-data

# - !grant
#   role: !group vault-synchronizer/lob-1/safe-2/consumers
#   member: !host vault-synchronizer-hosts/safe-2

# - !grant
#   role: !group vault-synchronizer/lob-2/safe-3/consumers
#   member: !host vault-synchronizer-hosts/safe-3

# - !grant
#   role: !group vault-synchronizer/lob-2/safe-4/consumers
#   member: !host vault-synchronizer-hosts/safe-4

# - !grant
#   role: !group vault-synchronizer/lob-2/safe-5/consumers
#   member: !host vault-synchronizer-hosts/safe-5
