- !policy
  id: vault-synchronizer-hosts
  body:
    - !policy
      id: lob-1
      owner: !group /vault-synchronizer/lob-1-admin
      body:
        - !policy
          id: safe-1
          owner: !group /vault-synchronizer/lob-1/safe-1-admin
          body:
          - !layer hosts
          - &lob-1-safe-1-hosts
            - !host host-1
          - !grant
            role: !layer hosts
            members: *lob-1-safe-1-hosts
        
    
- !grant
  role: !group vault-synchronizer/lob-1/safe-1/consumers
  members: !layer vault-synchronizer-hosts/lob-1/safe-1/hosts
  
