apiVersion: v1
kind: ConfigMap
metadata:
  name: secretless-config
  namespace: test-app
data:
  secretless.yml: |
    version: "2"
    services:
      pg:
        protocol: pg
        listenOn: tcp://0.0.0.0:5432
        credentials:
          username:
            from: conjur
            get: db-credentials/username
          password:
            from: conjur
            get: db-credentials/password
          address:
            literal: localhost:5433
        config: {}
    credentials:
      - name: conjur
        provider: conjur
        id: conjur

