#!/bin/bash -ex

account='demo'


function print_help() {
  cat << EOF

Provisions a Conjur cluster locally, using Docker.

Usage: start [options]

    --auto-failover     Configures the cluster for auto-failover
    --custom-certs      Installs custom certificates from the "files/certs" folder
    -h, --help          Shows this help message.
    --load-data         Loads sample policy along once th cluster
    --master-key        Encrypts certificates using a master key
    --tag <conjur-tag>  Starts a cluster with a particular appliance (defaults to 5.0-stable)

EOF
  exit
}

function master_cluster_hf_token() {
  local output=$(./cli conjur hostfactory tokens create --duration-minutes=30 conjur/cluster/conjur)
  echo $output | sed 1d | jq -r '.[0].token'
  # local master_uri='https://localhost'
  # local host_factory="$account:host_factory:conjur/cluster/conjur"
  #
  # local api_key=$(curl -k --user admin:secret $master_uri/authn/$account/login)
  #
  # local response=$(curl -k -X POST -d "$api_key" $master_uri/authn/$account/admin/authenticate)
  #
  # local token=$(echo -n "$response" | base64 | tr -d '\r\n')
  #
  # local hf_token=$(curl -k -X POST -H "Authorization: Token token=\"$token\"" \
  #     --data-urlencode "host_factory=$host_factory" \
  #     --data-urlencode "expiration=2019-08-04T22:27:20+00:00" \
  #     "$master_uri/host_factory_tokens" \
  #     | jq -r '.[0].token')
  #
  # echo $hf_token
}

# Determine which extra services should be loaded when working with authenticators
# export VERSION=5.2.2-20181029194559-7305fae
TAG=5.0-stable
AUTO_FAILOVER=false
LOAD_DATA=false
MASTER_KEY=false
CUSTOM_CERTS=false
while true ; do
  case "$1" in
    --auto-failover ) AUTO_FAILOVER=true ; shift ;;
    --load-data ) LOAD_DATA=true ; shift ;;
    --master-key ) MASTER_KEY=true ; shift ;;
    --custom-certs ) CUSTOM_CERTS=true ; shift ;;
    --tag ) shift ; TAG=$1 ; shift ;;
    -h | --help ) print_help ; shift ;;
     * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
  esac
done

export VERSION=$TAG

if [[ $AUTO_FAILOVER = true ]]; then
  docker-compose up -d --no-deps conjur-master-1.mycompany.local \
                                  conjur-master-2.mycompany.local \
                                  conjur-master-3.mycompany.local \
                                  conjur-master-4.mycompany.local \
                                  conjur-follower.mycompany.local
else
  docker-compose up -d --no-deps conjur-master-1.mycompany.local \
                                  conjur-master-2.mycompany.local \
                                  conjur-follower.mycompany.local
fi

docker-compose exec conjur-master-1.mycompany.local bash -c "
  evoke configure master \
  -h conjur-master-1.mycompany.local \
  -p secret $account
"

if [[ $AUTO_FAILOVER = true ]]; then
  ./cli conjur policy load --replace root policy/root.yml
  ./cli conjur policy load conjur policy/cluster.yml
fi
# exit

if [[ $CUSTOM_CERTS = true ]]; then
  docker-compose exec conjur-master-1.mycompany.local bash -c "
    evoke ca import -r /conjur_files/certs/ca-chain.cert.pem
    evoke ca import -k /conjur_files/certs/conjur-master-1.mycompany.local.key.pem -s /conjur_files/certs/conjur-master-1.mycompany.local.cert.pem
    evoke ca import -k /conjur_files/certs/conjur-master-2.mycompany.local.key.pem /conjur_files/certs/conjur-master-2.mycompany.local.cert.pem
    evoke ca import -k /conjur_files/certs/conjur-follower.mycompany.local.key.pem /conjur_files/certs/conjur-follower.mycompany.local.cert.pem
  "
  if [[ $AUTO_FAILOVER = true ]]; then
    docker-compose exec conjur-master-1.mycompany.local bash -c "
      evoke ca import -k /conjur_files/certs/conjur-master-3.mycompany.local.key.pem /conjur_files/certs/conjur-master-3.mycompany.local.cert.pem
      evoke ca import -k /conjur_files/certs/conjur-master-4.mycompany.local.key.pem /conjur_files/certs/conjur-master-4.mycompany.local.cert.pem
    "
  fi
fi

if [[ $AUTO_FAILOVER = true && $CUSTOM_CERTS = false ]]; then
  docker-compose exec conjur-master-1.mycompany.local bash -c "
    evoke ca issue conjur-master-2.mycompany.local
    evoke ca issue conjur-master-3.mycompany.local
    evoke ca issue conjur-master-4.mycompany.local
  "
fi

if [[ $CUSTOM_CERTS = false ]]; then
  docker-compose exec conjur-master-1.mycompany.local bash -c "
    evoke ca issue conjur-follower.mycompany.local
  "
fi

if [[ $MASTER_KEY = true ]]; then
  docker-compose exec conjur-master-1.mycompany.local bash -c "
    evoke keys encrypt /conjur_files/master-key
    evoke keys unlock /conjur_files/master-key
    sv start conjur
    /opt/conjur/evoke/bin/wait_for_conjur
  "
fi

# docker-compose exec conjur-master-1.mycompany.local bash -c "
#   evoke seed standby conjur-master-2.mycompany.local conjur-master-1.mycompany.local > /opt/conjur/backup/standby-seed-2.tar
#   evoke seed follower conjur-follower.mycompany.local > /opt/conjur/backup/follower-seed.tar
# "
# if [[ $AUTO_FAILOVER = true ]]; then
#   docker-compose exec conjur-master-1.mycompany.local bash -c "
#     evoke seed standby conjur-master-3.mycompany.local conjur-master-1.mycompany.local > /opt/conjur/backup/standby-seed-3.tar
#     evoke seed standby conjur-master-4.mycompany.local conjur-master-1.mycompany.local > /opt/conjur/backup/standby-seed-4.tar
#   "
# fi

# Setup the standby
hf_token=$(master_cluster_hf_token)

hostname='conjur-master-2.mycompany.local'
docker-compose exec -e hf_token=$hf_token -e hostname="conjur/$hostname" $hostname bash -c "
  /conjur_files/seed-configure demo https://conjur-master-1.mycompany.local $hf_token $hostname
"

# docker-compose exec conjur-master-2.mycompany.local bash -c "
#   evoke unpack seed /opt/conjur/backup/standby-seed-2.tar
# "
# if [[ $MASTER_KEY = true ]]; then
#   docker-compose exec conjur-master-2.mycompany.local bash -c "
#     evoke keys exec -m /conjur_files/master-key -- evoke configure standby
#   "
# else
#   docker-compose exec conjur-master-2.mycompany.local bash -c "
#     evoke configure standby
#   "
# fi

if [[ $AUTO_FAILOVER = true ]]; then
  # Setup the standby 3
  hostname='conjur-master-3.mycompany.local'
  docker-compose exec -e hf_token=$hf_token -e hostname="conjur/$hostname" $hostname bash -c "
    /conjur_files/seed-configure demo https://conjur-master-1.mycompany.local $hf_token $hostname
  "

  # docker-compose exec conjur-master-3.mycompany.local bash -c "
  #   evoke unpack seed /opt/conjur/backup/standby-seed-3.tar
  # "
  # if [[ $MASTER_KEY = true ]]; then
  #   docker-compose exec conjur-master-3.mycompany.local bash -c "
  #     evoke keys exec -m /conjur_files/master-key -- evoke configure standby
  #   "
  # else
  #   docker-compose exec conjur-master-3.mycompany.local bash -c "
  #     evoke configure standby
  #   "
  # fi

  # Setup the standby 4
  hostname='conjur-master-4.mycompany.local'
  docker-compose exec -e hf_token=$hf_token -e hostname="conjur/$hostname" $hostname bash -c "
    /conjur_files/seed-configure demo https://conjur-master-1.mycompany.local $hf_token $hostname
  "

  # docker-compose exec conjur-master-4.mycompany.local bash -c "
  #   evoke unpack seed /opt/conjur/backup/standby-seed-4.tar
  # "
  # if [[ $MASTER_KEY = true ]]; then
  #   docker-compose exec conjur-master-4.mycompany.local bash -c "
  #     evoke keys exec -m /conjur_files/master-key -- evoke configure standby
  #   "
  # else
  #   docker-compose exec conjur-master-4.mycompany.local bash -c "
  #     evoke configure standby
  #   "
  # fi

  docker-compose exec conjur-master-1.mycompany.local bash -c "
    evoke replication sync
  "

  docker-compose exec conjur-master-1.mycompany.local bash -c "
    evoke cluster enroll -n conjur-master-1.mycompany.local conjur
  "
  docker-compose exec conjur-master-2.mycompany.local bash -c "
    evoke cluster enroll -n conjur-master-2.mycompany.local -m conjur-master-1.mycompany.local conjur
  "
  docker-compose exec conjur-master-3.mycompany.local bash -c "
    evoke cluster enroll -n conjur-master-3.mycompany.local -m conjur-master-1.mycompany.local conjur
  "
  docker-compose exec conjur-master-4.mycompany.local bash -c "
    evoke cluster enroll -n conjur-master-4.mycompany.local -m conjur-master-1.mycompany.local conjur
  "
fi

# Setup the follower
docker-compose exec conjur-follower.mycompany.local bash -c "
  evoke unpack seed /opt/conjur/backup/follower-seed.tar
"
if [[ $MASTER_KEY = true ]]; then
  docker-compose exec conjur-follower.mycompany.local bash -c "
    evoke keys exec -m /conjur_files/master-key -- evoke configure follower
  "
else
  docker-compose exec conjur-follower.mycompany.local bash -c "
    evoke configure follower
  "
fi

rm -rf cli_cache
if [[ $LOAD_DATA = true ]]; then
  ./cli conjur policy load root policy/users.yml
  ./cli conjur policy load root policy/policy.yml
  ./cli conjur policy load staging policy/apps/myapp.yml
  ./cli conjur policy load production policy/apps/myapp.yml
  ./cli conjur policy load root policy/application_grants.yml
fi
