FROM ruby:2.7-alpine

# Install Docker-Compose
RUN apk add --no-cache docker-cli docker-cli-compose build-base bash jq curl libffi-dev

RUN mkdir -p /src
WORKDIR /src

COPY Gemfile /src/Gemfile
COPY Gemfile.lock /src/Gemfile.lock
RUN bundle install
