#!/bin/bash -eu

DB_SERVER_DNS=$(terraform output db_dns)

function main {
  install_ssh_user_ca
}

function install_ssh_user_ca {
   # TODO: Add host certificate CA to remove "StrictHostKeyChecking no" option

  # Copy CA certificate
  scp -i tmp/id_aws \
    -o "StrictHostKeyChecking no" \
    cas/ssh_users/id_ssh_users-cert.pub ubuntu@$DB_SERVER_DNS:~


  # Configure SSH User CA on host
  ssh -i tmp/id_aws \
    -o "StrictHostKeyChecking no" \
    ubuntu@$DB_SERVER_DNS /bin/bash << EOF

    # Add user for 'alice'
    sudo adduser --disabled-password --gecos "" alice

    # Add 'TrustedUserCAKeys' file
    sudo cp ~/id_ssh_users-cert.pub /etc/ssh/
    sudo sh -c """
      grep -q '^TrustedUserCAKeys' /etc/ssh/sshd_config && \
        sed -i 's~^TrustedUserCAKeys.*~TrustedUserCAKeys /etc/ssh/id_ssh_users-cert.pub~' /etc/ssh/sshd_config || \
        echo 'TrustedUserCAKeys /etc/ssh/id_ssh_users-cert.pub' >> /etc/ssh/sshd_config
    """

    # Restart sshd
    sudo service sshd restart
EOF

}

main
