version: "3"
services:
  conjur-master.mycompany.local:
    image: registry.tld/conjur-appliance:5.0-stable
    ports:
      - "443:443"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - backups:/opt/conjur/backup/
      - ./files:/conjur_files
    links:
      - ldap-server

  conjur-follower.mycompany.local:
    image: registry.tld/conjur-appliance:5.0-stable
    environment:
      CONJUR_AUTHENTICATORS: "authn-ldap/ldap-server,authn"
      CONJUR_AUTHN_URL: http://localhost/authn-ldap/ldap-server
    ports:
      - "444:443"
    security_opt:
        - "seccomp:unconfined"
    volumes:
      - backups:/opt/conjur/backup/
      - ./files:/conjur_files
    links:
      - ldap-server

  client:
    image: cyberark/conjur-cli:8
    working_dir:  -w /src/cli
    environment:
      CONJUR_APPLIANCE_URL: https://conjur-master.mycompany.local
      CONJUR_ACCOUNT: demo
      CONJUR_AUTHN_LOGIN: admin
    volumes:
      - .:/src/cli
      - ./cli_cache:/root

  ldap-server:
    image: osixia/openldap
    hostname: ldap-server
    command: --copy-service --loglevel debug
    environment:
      LDAP_ADMIN_PASSWORD: ldapsecret
      LDAP_TLS: "true"
      LDAP_TLS_CA_CRT_FILENAME: "ca-chain.crt"
      LDAP_TLS_ENFORCE: "true"
      LDAP_TLS_VERIFY_CLIENT: try
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./files/ldap:/opt/ldap
      - ./certs:/container/service/slapd/assets/certs

volumes:
  backups:
