#!/bin/bash -ex

function print_help() {
  cat << EOF

Provisions a Conjur cluster locally, using Docker.

Usage: start [options]

    -h, --help        Shows this help message.

EOF
  exit
}

while true ; do
  case "$1" in
    -h | --help ) print_help ; shift ;;
     * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
  esac
done

docker-compose up -d --no-deps conjur-master.mycompany.local conjur-follower.mycompany.local ldap-server

docker-compose exec conjur-master.mycompany.local bash -c "
  evoke configure master \
  -h conjur-master.mycompany.local \
  -p secret demo
"

master_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ldap-integration_conjur-master.mycompany.local_1)

docker-compose exec conjur-master.mycompany.local bash -c "
  evoke seed follower conjur-follower.mycompany.local > /opt/conjur/backup/follower-seed.tar
"

# Setup the follower
docker-compose exec conjur-follower.mycompany.local bash -c "
  evoke unpack seed /opt/conjur/backup/follower-seed.tar
"
docker-compose exec conjur-follower.mycompany.local bash -c "
  evoke configure follower
"


# if [[ $LOAD_DATA = true ]]; then
#   ./cli conjur policy load --replace root policy/users.yml
#   ./cli conjur policy load root policy/policy.yml
#   ./cli conjur policy load staging policy/apps/myapp.yml
#   ./cli conjur policy load production policy/apps/myapp.yml
#   ./cli conjur policy load root policy/application_grants.yml
# fi
