version: "3"
services:

  # nginx web server
  server:
    build: ./server
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: mutual-tls/server
      CA_SERVICE_ID: mutual-tls
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./server:/server
  
  # curl web client
  client:
    build: ./client
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: mutual-tls/client
      CA_SERVICE_ID: mutual-tls
    volumes:
      - ./client:/client
  
  # Service for generating our root and intermediate CA
  ca:
    build: ./ca
    volumes: 
      - ./ca:/tmp/ca

  conjur:
    image: cyberark/conjur
    command: server
    environment:
      DATABASE_URL: postgres://postgres@database/postgres
      CONJUR_DATA_KEY:
    depends_on: [ database ]
    ports:
      - "8080:80"
    expose:
      - "80"

  database:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  cli:
    image: cyberark/conjur-cli:8
    working_dir: /src/cli
    entrypoint: bash
    environment:
      CONJUR_APPLIANCE_URL: http://conjur
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin

    volumes:
      - ./cli:/src/cli
      - ./cli/cache:/root

volumes:
  certs:
