#!/bin/bash -eu

CONJUR_MASTER_PUBLIC_DNS=$(terraform output conjur_master_public)

docker run --rm -it -v "$(pwd):/data" \
  --entrypoint /bin/bash \
  -e "CONJUR_APPLIANCE_URL=https://${CONJUR_MASTER_PUBLIC_DNS}" \
  -e "CONJUR_ACCOUNT=puppet" \
  cyberark/conjur-cli:5
