#!/bin/bash -eu

PUPPET_AGENT_LINUX_HOST=$(terraform output puppet_agent_linux_public_dns)

ssh -i ~/.ssh/micahlee.pem \
    -o "StrictHostKeyChecking no" \
    "ec2-user@${PUPPET_AGENT_LINUX_HOST}" 
