#!/bin/bash -eu

: ${SSH_KEY_FILE?"Need to set SSH_KEY_FILE"}

PUPPET_MASTER_HOST=$(terraform output puppet_master_public_dns)

ssh -i "${SSH_KEY_FILE}" \
    -o "StrictHostKeyChecking no" \
    "ec2-user@${PUPPET_MASTER_HOST}" 
