#!/bin/ash -e

function _print_help() {
  cat << EOF

A tool which uses the DAP API to perform various tasks.

Usage: bin/api [options]

    --against-master            Runs command against the master (only relevant if command is an authenticate/read action)
    --authenticate-user         Login using the default username (admin) and password (MySecretP@ss1)
    --fetch-secrets             Fetches previously set variables (use '--against-master' if only master is available)
    -h, --help                  Shows this help message
    --load-policy               Loads a default set of policies to mimic a customer experience
    --load-policy-and-values    Loads policy and sets variable values (equivalent to running '--load-policy' and '--set-secrets')
    -p, --password <password>   Sets the password (default is 'MySecretP@ss1')
    --set-secrets               Sets variable values
    -u, --user <conjur-user>    Sets the username (default is 'admin')

EOF
  exit
}

function retrieve_authentication_token() {
  local user="$1"
  local api_key="$2"
  local url="${3:-$URL}"
  raw_token="$(curl -s -k -X POST -d $api_key "$url/authn/demo/$user/authenticate")"
  token=$(echo -n $raw_token | base64 | tr -d '\r\n')
  echo "$token"
}

function authenticate_user() {
  local user="$1"
  local password="$2"
  local url="${3:-$URL}"
  api_key="$(curl -s -k --user $user:$password "$url/authn/demo/login")"
  token=$(retrieve_authentication_token $user $api_key $url)
  echo "$token"
}

function load_policy() {
  local namespace="$1"
  local policy="$2"
  local token=$(authenticate_user $USER $PASSWORD $master_url)
  curl --header "Authorization: Token token=\"$token\"" \
        --insecure \
        --request POST \
        --data "$(cat $policy)" \
     "$master_url/policies/demo/policy/$namespace"
}

function set_variable() {
  local variable="$1"
  local value="$2"
  local token=$(authenticate_user $USER $PASSWORD $master_url)

  curl --header "Authorization: Token token=\"$token\"" \
        --insecure \
        --data "$value" \
        "$master_url/secrets/demo/variable/$variable"
}

function load_default_policy {
  load_policy 'root' 'policy/modular/root.yml'
  load_policy 'staging' 'policy/modular/apps/applications.yml'
  load_policy 'staging/my-app-1' 'policy/modular/apps/generic-application.yml'
  load_policy 'staging/my-app-1' 'policy/modular/services/pg-database.yml'
  load_policy 'staging/my-app-1' 'policy/modular/pg-entitlement.yml'
}

function load_default_values {
  set_variable 'staging/my-app-1/postgres-database/url' 'staging.mycompany-postgres.com/my-app'
  set_variable 'staging/my-app-1/postgres-database/port' '5432'
  set_variable 'staging/my-app-1/postgres-database/username' 'my-app'
  set_variable 'staging/my-app-1/postgres-database/password' 'secret-p@ssword'
}


function fetch_secrets {
  local variables="$1"
  local token=$(authenticate_user $USER $PASSWORD $URL)
  curl --header "Authorization: Token token=\"$token\"" \
        --insecure \
        --request GET \
        "$master_url/secrets?variable_ids=$variables"
}

function retrieve_variables {
  secrets="demo:variable:staging/my-app-1/postgres-database/url,demo:variable:staging/my-app-1/postgres-database/port,demo:variable:staging/my-app-1/postgres-database/username,demo:variable:staging/my-app-1/postgres-database/password"
  fetch_secrets $secrets #| jq .
}

function load_policy_and_set_variables {
  load_default_policy
  load_default_values
}

follower_url='http://conjur-follower.mycompany.local'
master_url='https://conjur-master.mycompany.local'
URL=$follower_url
USER='admin'
PASSWORD='MySecretP@ss1'
cmd=''

while true ; do
  case "$1" in
    -u | --user ) shift ; USER=$1 ; shift ;;
    -p | --password ) shift ; PASSWORD=$1 ; shift ;;
    --authenticate-user ) shift ; cmd="authenticate_user $USER $PASSWORD" ;;
    -h | --help ) _print_help ; shift ;;
    --load-policy-and-values ) shift ; cmd="load_policy_and_set_variables" ;;
    --load-policy ) shift ; cmd='load_default_policy' ;;
    --set-secrets ) shift ; cmd='load_default_values' ;;
    --against-master ) shift ; URL=$master_url ;;
    --fetch-secrets ) shift ; cmd="retrieve_variables" ;;
     * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
  esac
done

eval $cmd
