apiVersion: v1
kind: Service
metadata:
  name: conjur-follower-node-port
  namespace: cyberark-conjur
  labels:
    app: conjur-follower
spec:
  type: NodePort
  selector:
    app: conjur-follower
  ports:
    - port: 9443
      nodePort: 30443
      protocol: TCP
      name: https
