kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: conjur-intro-k8s-follower
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30443
        hostPort: 451
        protocol: TCP
