#!/bin/bash -ex

docker-compose up -d --no-deps conjur-master conjur-standby conjur-follower

docker-compose exec conjur-master bash -c "
  evoke configure master \
  -h conjur-master \
  -p secret demo
"

docker-compose exec conjur-master bash -c "
  evoke seed standby conjur-standby > /opt/conjur/backup/standby-seed.tar
  evoke seed follower conjur-follower > /opt/conjur/backup/follower-seed.tar
"

docker-compose exec conjur-standby bash -c "
  evoke unpack seed /opt/conjur/backup/standby-seed.tar
  evoke configure standby
"

docker-compose exec conjur-follower bash -c "
  evoke unpack seed /opt/conjur/backup/follower-seed.tar
  evoke configure follower
"
