---
apiVersion: v1
kind: Pod
metadata:
  name: test-app
  namespace: {{ .Release.Namespace }}
  annotations:
    conjur.org/secrets: |
{{ .Values.conjur.secrets | indent 6 }}
spec:
  serviceAccountName: {{ .Values.serviceAccount.name }}
  containers:
    - name: app
      image: alpine:latest
      imagePullPolicy: Always
      command: [ "/bin/sh", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - name: conjur-csi-provider-volume
          mountPath: /mnt/secrets-store
          readOnly: true
      securityContext:
        allowPrivilegeEscalation: false
  volumes:
    - name: conjur-csi-provider-volume
      csi:
        driver: 'secrets-store.csi.k8s.io'
        readOnly: true
        volumeAttributes:
          secretProviderClass: {{ .Values.secretProviderClass.name }}
