---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: conjur
  parameters:
    conjur.org/configurationVersion: {{ .Values.conjur.configurationVersion }}
    account: {{ .Values.conjur.account }}
    applianceUrl: {{ .Values.conjur.applianceUrl }}
    authnId: {{ .Values.conjur.authnId }}
    secrets: |
{{ .Values.conjur.secrets | indent 6 }}
    sslCertificate: |
{{ .Values.conjur.sslCertificate | indent 6 }}
