#!/bin/bash -e

source ./config

function main() {
  while true ; do
    case "$1" in
      -h | --help ) print_help ; shift ;;
      * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
    esac
  done

  start_demo
}


function print_help() {
  cat << EOF

Provisions a Conjur cluster locally, using Docker.

Usage: start [options]

    -h, --help        Shows this help message.

EOF
  exit
}

function start_demo() {
  configure_master
  load_demo_policy
}

function configure_master() {
  docker-compose up -d --no-deps conjur-master

  docker-compose exec conjur-master bash -c "
    evoke configure master \
    -h conjur-master \
    -p "${CONJUR_ADMIN_PASSWORD}" "${CONJUR_ACCOUNT}"
  "
}

function load_demo_policy() {
  ./cli conjur policy load --replace root policy/01_root.yml

  # Ops Secrets
  ./cli conjur policy load ops policy/ops/main.yml
  ./cli conjur policy load ops/ca policy/ops/ca/main.yml
  ./cli conjur policy load ops/ca/web-server policy/ops/ca/web-server/main.yml

  # Databases
  ./cli conjur policy load database policy/database/main.yml

  # Web Servers
  ./cli conjur policy load server policy/server/main.yml

  ./cli conjur policy load root policy/02_users.yml
  ./cli conjur policy load root policy/03_entitlements.yml
}

main
