#!/bin/ash -e
set -o pipefail

config_path="/src/configuration"
certificate_path="/src/certificates"

# Generated Cert paths
root_destination="$certificate_path/root_ca/ca"
intermediate_destination="$certificate_path/intermediate_ca/intermediate"
master_destination="$certificate_path/dap_master/dap-master"
follower_destination="$certificate_path/dap_follower/dap-follower"

GENERATE_CA=true
GENERATE_SERVER=true
FORCE=false

main() {
  echo "$@"
  while true ; do
    case "$1" in
      --rotate-server ) GENERATE_CA=false; shift ;;
      --force ) FORCE=true; shift ;;
      -h | --help ) print_help ; shift ;;
      * ) if [ -z "$1" ]; then break; else echo "$1 is not a valid option"; exit 1; fi;;
    esac
  done

  echo "***TEMP*** generate-certs-script"
  echo "***TEMP*** GENERATE_CA: $GENERATE_CA"
  echo "***TEMP*** FORCE:       $FORCE"
  create_folders
  generate_certificates
}

print_help() {
  cat << EOF

Generates a Root, Intermediate, DAP Master and Follower certificates

Usage: bin/generate-certs [options]

    -h, --help        Shows this help message.
    --rotate-server   Only generate new server certificates
    --force           Generate certificates even if they already exist

EOF
  exit
}

create_folders() {
  echo "***TEMP*** create_folders()"
  folders='root_ca intermediate_ca dap_master dap_follower'
  for folder in $folders ; do
    mkdir -p "$certificate_path/$folder"
  done
}

generate_certificates() {
  echo "***TEMP*** In generate_certificates()"
  echo "======================================================"
  ls -l "$config_path"
  echo "======================================================"
  if [ "$GENERATE_CA" = true ]; then
    # Generate Root Certificate if it does not exist
    if [ ! -f "$root_destination.pem" ] || [ "$FORCE" = true ]; then
      echo "***TEMP*** Generate Root certificate"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
      cfssl gencert -initca "$config_path/root_ca.json" | \
      cfssljson -bare $root_destination
    fi

    # Generate and sign intermediate certificate if it does not exist
    if [ ! -f "$intermediate_destination.pem" ] || [ "$FORCE" = true ]; then
      # Generate Intermediate Certificate
      echo "***TEMP*** Generate intermediate certificate"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
      cfssl gencert -initca $config_path/intermediate_ca.json | \
      cfssljson -bare $intermediate_destination

      # Sign Intermediate with Root
      echo "***TEMP*** Sign intermediate with Root"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
      cfssl sign \
        -ca $root_destination.pem \
        -ca-key $root_destination-key.pem \
        -config $config_path/cfssl.conf \
        -profile intermediate_ca \
        $intermediate_destination.csr | cfssljson -bare $intermediate_destination
    fi

    cat $certificate_path/intermediate_ca/intermediate.pem \
      $certificate_path/root_ca/ca.pem > \
      $certificate_path/ca-chain.pem
  fi

  # Generate and sign master certificate w/ intermediate
  echo "***TEMP*** Generate and sign master cert w/ intermediate"
  if [ "$GENERATE_SERVER" = true ]; then
    if [ ! -f "$master_destination-key.pem" ]; then
      echo "***TEMP*** Calling generate_master_key"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
      generate_master_key      
      echo "***TEMP*** Return from generate_master_key"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
    fi

    if [ ! -f "$master_destination.pem" ] || [ "$FORCE" = true ]; then
      echo "***TEMP*** Calling generate_master_csr"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
      generate_master_csr
      echo "***TEMP*** Return from generate_master_csr"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
      echo "***TEMP*** Calling issue_master_certificate"
      issue_master_certificate
      echo "***TEMP*** Return from issue_master_certificate"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
    fi
    
    if [ ! -f "$follower_destination-key.pem" ]; then
      echo "***TEMP*** Calling generate_follower_key"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
      generate_follower_key      
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
      echo "***TEMP*** Return from generate_follower_key"
    fi

    # Generate and sign follower certificate w/ intermediate
    echo "***TEMP*** Generate and sign follower cert w/ intermediate"
    if [ ! -f "$follower_destination.pem" ] || [ "$FORCE" = true ]; then
      echo "***TEMP*** Calling generate_follower_csr"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
      generate_follower_csr
      echo "***TEMP*** Return from generate_follower_csr"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
      echo "***TEMP*** Calling issue_follower_certificate"
      issue_follower_certificate
      echo "***TEMP*** Return from issue_follower_certificate"
      echo "======================================================"
      ls -l "$config_path"
      echo "======================================================"
    fi
  fi
  echo "***TEMP*** Returning from generate_certificates()"
  echo "======================================================"
  ls -l "$config_path"
  echo "======================================================"
}

generate_master_key() {
  cfssl genkey \
    -config $config_path/cfssl.conf \
    $config_path/dap-master.json | cfssljson -bare $master_destination
}

generate_master_csr() {
  cfssl gencsr \
    -key "$master_destination-key.pem" \
    $config_path/dap-master.json | cfssljson -bare $master_destination
}

issue_master_certificate() {
  cfssl sign \
    -ca $intermediate_destination.pem \
    -ca-key $intermediate_destination-key.pem \
    -config $config_path/cfssl.conf \
    -profile=peer \
    $master_destination.csr | cfssljson -bare $master_destination
}

generate_follower_key() {
  #cfssl genkey \
  #  -config $config_path/cfssl.conf \
  #  $config_path/dap-follower.json | cfssljson -bare $follower_destination
  echo "***TEMP*** In generate_follower_key(). config_path: $config_path"
  echo "***TEMP*** Files in $config_path:"
  echo "***TEMP*** ================================"
  ls -l "$config_path"
  echo "***TEMP*** ================================"
  echo "***TEMP*** dap-follower.json content:"
  echo "***TEMP*** ================================"
  cat $config_path/dap-follower.json
  echo "***TEMP*** ================================"
  cfssl genkey \
    -config $config_path/cfssl.conf \
    $config_path/dap-follower.json > temp-key-json
  echo "***TEMP*** Output of 'cfssl genkey...':"
  echo "***TEMP*** ================================"
  cat temp-key-json
  echo "***TEMP*** ================================"
  echo "***TEMP*** Calling 'cfssljson'...', follower_destination: $follower_destination"
  cat temp-key-json | cfssljson -bare $follower_destination
}

generate_follower_csr() {
  cfssl gencsr \
    -key "$follower_destination-key.pem" \
    $config_path/dap-follower.json | cfssljson -bare $follower_destination
}

issue_follower_certificate() {
  cfssl sign \
    -ca $intermediate_destination.pem \
    -ca-key $intermediate_destination-key.pem \
    -config $config_path/cfssl.conf \
    -profile=peer \
    $follower_destination.csr | cfssljson -bare $follower_destination
}

main "$@"
