#!/bin/bash -e

host="https://ec2-34-224-2-198.compute-1.amazonaws.com"

cmd="$@"
docker run \
  --rm \
  -it \
  --entrypoint /bin/bash \
  -e "CONJUR_APPLIANCE_URL=$host" \
  -e "CONJUR_ACCOUNT=demo" \
  -e "CONJUR_AUTHN_LOGIN=admin" \
  -v "$(pwd)/policy:/policy" \
  -v "$(pwd)/cli_cache:/root" \
  cyberark/conjur-cli:5 -c "
    if [ ! -e /root/conjur-demo.pem ]; then
      conjur init -u $host
    fi
    conjur authn login -u admin -p secret
    eval exec \"$cmd\"
  "
